version: '3.7'

services:
  totel_api: 
    image: postgres
    container_name: totel_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_DB=totelapi
    volumes:
      - pgdata:/data/postgres
  app: 
    build: .
    command: npm run dev
    container_name: totel
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - totel_api
    depends_on:
      - totel_api
volumes:
  pgdata:
    driver: local